handling pyxis version check errors to display preflight release url
redhat-openshift-ecosystem/openshift-preflight pull request #1135
Opened 2024-03-12 20:46 UTC by acornett21

- Handling the two possible 400 series error messages.
- Displaying the latest preflight release URL to the user.

**Note: I'm not sure if how I'm using the logger here is correct for this part of the application. Suggestions welcome.**

2024-03-14 21:14 UTC, komish requested changes
Overall, LGTM - just a couple of suggestions.

2024-03-14 21:33 UTC, acornett21 commented on internal/pyxis/pyxis.go
> +			logger.V(log.DBG).Error(errors.New("invalid preflight version, please please download the latest version and re-submit"), "release-url", preflightReleaseURL)
Base logging is what I was thinking as well, but wanted to be sure.

2024-03-14 22:02 UTC, acornett21 commented on internal/pyxis/pyxis.go
> +	preflightReleaseURL = "https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/latest"
Good call I never realized this was exposed.

2024-03-14 22:06 UTC, acornett21 commented on internal/pyxis/pyxis.go
> +			(strings.Contains(string(body), "not recognized") || strings.Contains(string(body), "not supported")) {
I refactored this out LMK what you think.

2024-03-18 16:50 UTC, komish approved these changes
/lgtm

2024-04-10 16:37 UTC, closed without merging