updating gitignore to include test file we create as part of runnable tests
redhat-openshift-ecosystem/openshift-preflight pull request #434
Opened 2022-02-23 16:38 UTC by acornett21

- updating the gitignore to include files we create during runnable tests.
- we remove this file after the test is over, but during development/testing sometimes this file stays around and its better that it doesn't get committed.

Signed-off-by: Adam D. Cornett <adc@redhat.com>

2022-02-23 19:22 UTC, bcrochet requested changes
I'd prefer to see us write this to a tmp dir rather than ignore it here.

2022-02-23 22:59 UTC, acornett21 commented
> I'd prefer to see us write this to a tmp dir rather than ignore it here.

This is a file that `podman` writes and I don't see an argument to change where it's written to, but can look more later.

2022-02-24 20:06 UTC, bcrochet commented
> > I'd prefer to see us write this to a tmp dir rather than ignore it here.
> 
> This is a file that `podman` writes and I don't see an argument to change where it's written to, but can look more later.

You would need to not use the '--files' and read/write the file from stdout.

2022-02-28 20:41 UTC, bcrochet commented
Ignoring this for now, since these checks are no longer enabled.

2022-02-28 20:41 UTC, closed without merging