Introduce context param throughout the codebase
redhat-openshift-ecosystem/openshift-preflight pull request #499
Opened 2022-03-17 13:20 UTC by bcrochet

Context should be shared from the highest level down through all
calls. This is the beginning of making that a reality. Once context
is being passed, we can start to add things to the context, like
params from viper, so that the parts of the codebase that do not
have to do with the CLI don't know anything about viper. Consider
it a separation of concerns.

Signed-off-by: Brad P. Crochet <brad@redhat.com>

2022-03-17 16:06 UTC, acornett21 requested changes
This is a great start to a refactor, just a few questions for a few places.

2022-03-17 18:52 UTC, bcrochet commented on certification/internal/engine/engine.go
Yes. Good call. The RPMmanifest one hit because of the usage of rpm.GetPackageList()

2022-03-17 18:52 UTC, bcrochet commented on certification/internal/policy/operator/deployable_by_olm.go
>  	if report, err := bundle.ValidateBundle(p.OperatorSdkEngine, bundleRef.ImageFSPath); err != nil || !report.Passed {
Yes. Will add...

2022-03-18 15:59 UTC, acornett21 approved these changes

2022-03-18 15:59 UTC, merged