Test that config file is read from
redhat-openshift-ecosystem/openshift-preflight pull request #956
Opened 2023-04-13 13:47 UTC by bcrochet

This checks that the config file is actually read, and that the values contained in it are what makes it into viper.

Fixes #932

2023-04-13 13:51 UTC, skattoju approved these changes

2023-04-13 14:05 UTC, acornett21 approved these changes

2023-04-13 14:53 UTC, acornett21 approved these changes

2023-04-14 14:46 UTC, komish approved these changes
/lgtm

2023-04-14 14:52 UTC, acornett21 requested changes

2023-04-14 14:52 UTC, acornett21 commented on cmd/preflight/cmd/root.go
> -		}
This code should stay, the intent is to have the log file in the `tar` and at the default location.

2023-04-14 21:14 UTC, acornett21 approved these changes

2023-04-14 21:15 UTC, merged